### ISSUE TITLE
Unable to compile under MSYS2 Windows 10 Pro

### ISSUE THREAD

**Issue by caecos** [Xenakios/Poly_AudibleInstruments#6]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
make: clang: No such file or directory
make: clang: No such file or directory
make: clang: No such file or directory
make: clang: No such file or directory
C:/msys64/Rack-SDK/arch.mk:19: *** Could not determine architecture of . Try hacking around in arch.mk. Arrêt.

**Comment by xandramax** [comment]
It's the same under Windows 7. This is caused by the addition of 2 lines to the beginning of the makefile in commit 1cf8aaf9b65aa1b13e2800bc7bcbdd4c12914cbb. Just comment out these two lines and it will build.

**Comment by caecos** [comment]
Can you show me how to do it?

**Comment by caecos** [comment]
Thank's...it works...
