### ISSUE TITLE
Won't compile with MSYS2 on Windows 10 Pro

### ISSUE THREAD

**Issue by caecos** [Xenakios/Poly_AudibleInstruments#7]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
make: clang: No such file or directory
make: clang: No such file or directory
make: clang: No such file or directory
make: clang: No such file or directory
C:/msys64/Rack-SDK/arch.mk:19: *** Could not determine architecture of . Try hacking around in arch.mk. Arrêt.

**Comment by SteveRussell33** [comment]
Comment out the 1st two lines of the makefile like this:
```
#CC := clang
#CXX := clang++
```

**Comment by caecos** [comment]
I forgot to do it... thanks to remember it to me...

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Steve Russell <notifications@github.com>
Envoyé : Sunday, May 10, 2020 11:58:41 PM
À : Xenakios/Poly_AudibleInstruments <Poly_AudibleInstruments@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Author <author@noreply.github.com>
Objet : Re: [Xenakios/Poly_AudibleInstruments] Won't compile with MSYS2 on Windows 10 Pro (#7)


Comment out the 1st two lines of the makefile like this:

#CC := clang
#CXX := clang++

**Comment by Xenakios** [comment]
The current git head is not meant for end users who want to compile from source. I've been experimenting with new modules and features, as well as using Clang to compile. I should probably put all that stuff into a new branch.

**Comment by SteveRussell33** [comment]
I agree with you about putting certain stuff on a different branch. I, for the most part, build everything for Rack anyway, so I'm personally used to experimental modules, code, features and trying out fixes etc.
I'll leave that for you to decide; in the mean time I'm liking the work you're doing in this repo. Thanks.
