### ISSUE TITLE
latest code crashes Rack when browser is opened

### ISSUE THREAD

**Issue by davephillips** [Xenakios/Poly_AudibleInstruments#8]
Greetings, and my compliments for the work you're doing on the Plaits GUI, it looks very cool. The latest commit builds okay but alas, it crashes Rack when I open the modules browser. I'm on Ubuntu 18.04, running VCV Rack v1.dev. Let me know if you need more information. I did test for the behavior several times, everything works fine when I remove the Poly_Audible plugin.

Best regards,

Dave Phillips

**Comment by Xenakios** [comment]
This should now be fixed.

**Comment by davephillips** [comment]
Yep, that fixed it. Thank you !
